/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import back_cover from './back_cover.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(back_cover);
  return [{type:'raw', geometry:nodes.back_cover.geometry, material: nodes.back_cover.material}]
  
}
useGLTF.preload(back_cover)