/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import caster_base2 from './caster_base2.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(caster_base2);
  return [{type:'raw', geometry:nodes.caster_base2.geometry, material: nodes.caster_base2.material}]
  
}
useGLTF.preload(caster_base2)