/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import caswheel from './caswheel.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(caswheel);
  return [{type:'raw', geometry:nodes.caswheel.geometry, material: nodes.caswheel.material}]
  
}
useGLTF.preload(caswheel)