/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import finger from './finger.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(finger);
  return [{type:'raw', geometry:nodes.finger.geometry, material: nodes.finger.material}]
  
}
useGLTF.preload(finger)