/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import finger_tip from './finger_tip.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(finger_tip);
  return [{type:'raw', geometry:nodes.finger_tip.geometry, material: nodes.finger_tip.material}]
  
}
useGLTF.preload(finger_tip)