/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import head from './head.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(head);
  return [{type:'raw', geometry:nodes.head.geometry, material: nodes.head.material}]
  
}
useGLTF.preload(head)