/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import hip from './hip.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(hip);
  return [{type:'raw', geometry:nodes.hip.geometry, material: nodes.hip.material}]
  
}
useGLTF.preload(hip)