/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import link6G from './link6G.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(link6G);
  return [{type:'raw', geometry:nodes.link6G.geometry, material: nodes.link6G.material}]
  
}
useGLTF.preload(link6G)