/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import link56 from './link56.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(link56);
  return [{type:'raw', geometry:nodes.link56.geometry, material: nodes.link56.material}]
  
}
useGLTF.preload(link56)