/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import link34 from './link34.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(link34);
  return [{type:'raw', geometry:nodes.link34.geometry, material: nodes.link34.material}]
  
}
useGLTF.preload(link34)