/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import link45 from './link45.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(link45);
  return [{type:'raw', geometry:nodes.link45.geometry, material: nodes.link45.material}]
  
}
useGLTF.preload(link45)