/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import link12 from './link12.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(link12);
  return [{type:'raw', geometry:nodes.link12.geometry, material: nodes.link12.material}]
  
}
useGLTF.preload(link12)