/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import lower from './lower.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(lower);
  return [{type:'raw', geometry:nodes.lower.geometry, material: nodes.lower.material}]
  
}
useGLTF.preload(lower)