/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import p_base from './p_base.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(p_base);
  return [{type:'raw', geometry:nodes.p_base.geometry, material: nodes.p_base.material}]
  
}
useGLTF.preload(p_base)