/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import p_grip from './p_grip.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(p_grip);
  return [{type:'raw', geometry:nodes.p_grip.geometry, material: nodes.p_grip.material}]
  
}
useGLTF.preload(p_grip)