/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import platform_LIO_backup from './platform_LIO_backup.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(platform_LIO_backup);
  return [{type:'raw', geometry:nodes.platform_LIO_backup.geometry, material: nodes.platform_LIO_backup.material}]
  
}
useGLTF.preload(platform_LIO_backup)