/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import r200 from './r200.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(r200);
  return [{type:'raw', geometry:nodes.r200.geometry, material: nodes.r200.material}]
  
}
useGLTF.preload(r200)