/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import swivel2 from './swivel2.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(swivel2);
  return [{type:'raw', geometry:nodes.swivel2.geometry, material: nodes.swivel2.material}]
  
}
useGLTF.preload(swivel2)