/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import torso from './torso.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(torso);
  return [{type:'raw', geometry:nodes.torso.geometry, material: nodes.torso.material}]
  
}
useGLTF.preload(torso)