/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import upper from './upper.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(upper);
  return [{type:'raw', geometry:nodes.upper.geometry, material: nodes.upper.material}]
  
}
useGLTF.preload(upper)