/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import link_puller from './link_puller.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(link_puller);
  return [{type:'raw', geometry:nodes.link_puller.geometry, material: nodes.link_puller.material}]
  
}
useGLTF.preload(link_puller)