/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import link_left_wheel from './link_left_wheel.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(link_left_wheel);
  return [{type:'raw', geometry:nodes.link_left_wheel.geometry, material: nodes.link_left_wheel.material}]
  
}
useGLTF.preload(link_left_wheel)