/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import link_lift from './link_lift.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(link_lift);
  return [{type:'raw', geometry:nodes.link_lift.geometry, material: nodes.link_lift.material}]
  
}
useGLTF.preload(link_lift)