/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import link_wrist_yaw_bottom from './link_wrist_yaw_bottom.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(link_wrist_yaw_bottom);
  return [{type:'raw', geometry:nodes.link_wrist_yaw_bottom.geometry, material: nodes.link_wrist_yaw_bottom.material}]
  
}
useGLTF.preload(link_wrist_yaw_bottom)