/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import link_wrist_yaw from './link_wrist_yaw.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(link_wrist_yaw);
  return [{type:'raw', geometry:nodes.link_wrist_yaw.geometry, material: nodes.link_wrist_yaw.material}]
  
}
useGLTF.preload(link_wrist_yaw)