/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import link_respeaker from './link_respeaker.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(link_respeaker);
  return [{type:'raw', geometry:nodes.link_respeaker.geometry, material: nodes.link_respeaker.material}]
  
}
useGLTF.preload(link_respeaker)