/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import link_gripper_finger_right from './link_gripper_finger_right.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(link_gripper_finger_right);
  return [{type:'raw', geometry:nodes.link_gripper_finger_right.geometry, material: nodes.link_gripper_finger_right.material}]
  
}
useGLTF.preload(link_gripper_finger_right)