/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import link_straight_gripper from './link_straight_gripper.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(link_straight_gripper);
  return [{type:'raw', geometry:nodes.link_straight_gripper.geometry, material: nodes.link_straight_gripper.material}]
  
}
useGLTF.preload(link_straight_gripper)