/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import link_wrist_pitch from './link_wrist_pitch.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(link_wrist_pitch);
  return [{type:'raw', geometry:nodes.link_wrist_pitch.geometry, material: nodes.link_wrist_pitch.material}]
  
}
useGLTF.preload(link_wrist_pitch)