/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import omni_wheel_m from './omni_wheel_m.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(omni_wheel_m);
  return [{type:'raw', geometry:nodes.omni_wheel_m.geometry, material: nodes.omni_wheel_m.material}]
  
}
useGLTF.preload(omni_wheel_m)