/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import link_head from './link_head.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(link_head);
  return [{type:'raw', geometry:nodes.link_head.geometry, material: nodes.link_head.material, scale: [1,1,1], rotation: [0,0,0]}]
  
}
useGLTF.preload(link_head)