/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import link_head_tilt from './link_head_tilt.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(link_head_tilt);
  return [{type:'raw', geometry:nodes.link_head_tilt.geometry, material: nodes.link_head_tilt.material, scale: [1,1,1], rotation: [0,0,0]}]
  
}
useGLTF.preload(link_head_tilt)