/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import link_gripper_finger_left from './link_gripper_finger_left.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(link_gripper_finger_left);
  return [{type:'raw', geometry:nodes.link_gripper_finger_left.geometry, material: nodes.link_gripper_finger_left.material, scale: [1,1,1], rotation: [0,0,0]}]
  
}
useGLTF.preload(link_gripper_finger_left)