/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import link_dry_erase_holder from './link_dry_erase_holder.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(link_dry_erase_holder);
  return [{type:'raw', geometry:nodes.link_dry_erase_holder.geometry, material: nodes.link_dry_erase_holder.material}]
  
}
useGLTF.preload(link_dry_erase_holder)