/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import link_mast from './link_mast.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(link_mast);
  return [{type:'raw', geometry:nodes.link_mast.geometry, material: nodes.link_mast.material}]
  
}
useGLTF.preload(link_mast)