/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import link_camera from './link_camera.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(link_camera);
  return [{type:'raw', geometry:nodes.link_camera.geometry, material: nodes.link_camera.material}]
  
}
useGLTF.preload(link_camera)