/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import link_aruco_top_wrist from './link_aruco_top_wrist.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(link_aruco_top_wrist);
  return [{type:'raw', geometry:nodes.link_aruco_top_wrist.geometry, material: nodes.link_aruco_top_wrist.material}]
  
}
useGLTF.preload(link_aruco_top_wrist)