/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import link_aruco_shoulder from './link_aruco_shoulder.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(link_aruco_shoulder);
  return [{type:'raw', geometry:nodes.link_aruco_shoulder.geometry, material: nodes.link_aruco_shoulder.material, scale: [1,1,1], rotation: [0,0,0]}]
  
}
useGLTF.preload(link_aruco_shoulder)